image: node:18
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run docs:build
    # - mkdir .public
    # - cp -r .vitepress/dist/* .public
    # - rm -rf .vitepress/dist
    # - mv .public public
  artifacts:
    paths:
      - .vitepress/dist
  publish: .vitepress/dist
  only:
    - main